type = "javascript"
workers_dev = true
account_id = "2a09613716e511a8fe8ca74abc084762"

[triggers]
crons = ["*/15 * * * *"]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.prod]
name = "bszet-vplan"

kv_namespaces = [
    { binding = "BSZET_VPLAN", id = "6a91e1aeade04159a26665cf7fe52518" }
]

[env.staging]
name = "bszet-vplan-staging"

kv_namespaces = [
    { binding = "BSZET_VPLAN", id = "ad46f5f8b0334fde966c0d59aad2f285" }
]
