import {
  BLOCK_1,
  BLOCK_2,
  BLOCK_3,
  BLOCK_4,
  BLOCK_5,
  CH_1,
  CH_2,
  Bio_1,
  Bio_2,
  PH_1,
  PH_2,
  W_R,
  INFO,
  BK_1,
  BK_2,
  INFO_1,
  INFO_2,
  REL,
  D,
  EN,
  ETH,
  FRZ,
  GE,
  LIT,
  MA,
  RU,
  SP,
  IS,
  F_EN,
  Timetable,
} from "../domain";

export const IG21: Timetable = {
  mon: [
    { time: BLOCK_1, subject: MA, place: "B 314"},
    { time: BLOCK_2, subject: GE, place: "B 10" },
    { time: BLOCK_3, subject: IS, place: "B 3" },
    { time: BLOCK_4, subject: CH_1, place: "B 9" },
    { time: BLOCK_4, subject: Bio_1, place: "B 12", },
  ],
  tue: [
    { time: BLOCK_1, subject: CH_2, place: "B 9" },
    { time: BLOCK_1, subject: PH_1, place: "B 112", },
    { time: BLOCK_2, subject: W_R, place: "B 106" },
    { time: BLOCK_3, subject: INFO, place: "B 3" },
    { time: BLOCK_4, subject: MA, place: "B 314", iteration: 1},
    { time: BLOCK_4, subject: BK_1, place: "A 06", iteration: 2 },
    { time: BLOCK_4, subject: INFO_2, place: "B 3", iteration: 2 },
  ],
  wed: [
    { time: BLOCK_1, subject: FRZ, place: "B 8" },
    { time: BLOCK_1, subject: RU, place: "B 4" },
    { time: BLOCK_2, subject: D, place: "B 4", iteration: 1 },
    { time: BLOCK_2, subject: EN, place: "B 4", iteration: 2 },
    { time: BLOCK_3, subject: IS, place: "B 3", },
    { time: BLOCK_4, subject: BK_2, place: "A 06", iteration: 1 },
    { time: BLOCK_4, subject: LIT, place: "B 05/B 14", iteration: 1 },
  ],
  thu: [
    { time: BLOCK_1, subject: ETH, place: "B 8", iteration: 1 },
    { time: BLOCK_1, subject: REL, place: "B 11", iteration: 1 },
    { time: BLOCK_1, subject: F_EN, place: "B 114", iteration: 2 },
    { time: BLOCK_2, subject: D, place: "B 4" },
    { time: BLOCK_3, subject: EN, place: "B 8" },
    { time: BLOCK_4, subject: INFO_1, place: "B 3", iteration: 1 },
    { time: BLOCK_4, subject: SP, place: "117. GS", iteration: 2 },
  ],
  fri: [
    { time: BLOCK_1, subject: FRZ, place: "B 8" },
    { time: BLOCK_1, subject: RU, place: "B 4" },
    { time: BLOCK_2, subject: D, place: "B 4" },
    { time: BLOCK_3, subject: MA, place: "B 308" },
    { time: BLOCK_4, subject: Bio_2, place: "B 12"},
    { time: BLOCK_4, subject: PH_2, place: "B 111" },
  ],
};
