import {
  BK_1,
  BK_2,
  BlOCK_1,
  BlOCK_2,
  BlOCK_3,
  BlOCK_4,
  BlOCK_5,
  CH,
  D,
  EN,
  ETH,
  FRZ,
  GE,
  IS,
  LF_1_2,
  LF_5,
  LF_6,
  LIT,
  MA,
  PH,
  room,
  RU,
  SP,
  Timetable,
  W_R,
} from "../domain";

export const IGD21: Timetable = {
  mon: [
    { time: BlOCK_2, subject: W_R, place: room("B", 8) },
    { time: BlOCK_3, iteration: 1, subject: EN, place: room("B", 12) },
    { time: BlOCK_3, iteration: 2, subject: MA, place: room("B", 10) },
    { time: BlOCK_4, subject: LF_6, place: room("B", 411), group: 1 },
    { time: BlOCK_4, subject: IS, place: room("B", 3), group: 2 },
    { time: BlOCK_5, iteration: 2, subject: BK_1, place: room("A", "06") },
    { time: BlOCK_5, iteration: 2, subject: LIT, place: room("B", 4) },
  ],
  tue: [
    { time: BlOCK_1, subject: MA, place: room("B", 12) },
    { time: BlOCK_2, subject: EN, place: room("B", 204) },
    { time: BlOCK_3, subject: LF_1_2, place: room("B", "03") },
    { time: BlOCK_4, iteration: 1, subject: BK_2, place: room("A", "06") },
    { time: BlOCK_4, iteration: 2, subject: SP, place: "Kästner" },
  ],
  wed: [
    { time: BlOCK_1, subject: GE, place: room("B", 108) },
    { time: BlOCK_2, subject: IS, place: room("B", 3) },
    { time: BlOCK_3, iteration: 1, subject: ETH, place: room("B", 306) },
    { time: BlOCK_3, iteration: 2, subject: LF_5, place: room("B", 405) },
    { time: BlOCK_4, subject: FRZ, place: room("A", 102) },
    { time: BlOCK_4, subject: RU, place: room("B", 4) },
  ],
  thu: [
    { time: BlOCK_1, subject: D, place: room("B", 6) },
    { time: BlOCK_2, subject: MA, place: room("B", 10) },
    { time: BlOCK_3, subject: IS, place: room("B", 3) },
    { time: BlOCK_4, subject: PH, place: room("B", 110) },
  ],
  fri: [
    { time: BlOCK_1, subject: LF_6, place: room("B", 411), group: 1 },
    { time: BlOCK_1, subject: IS, place: room("B", 312), group: 2 },
    { time: BlOCK_2, subject: CH, place: room("B", 9) },
    { time: BlOCK_3, subject: D, place: room("B", 6) },
    { time: BlOCK_4, subject: FRZ, place: room("A", 102) },
    { time: BlOCK_4, subject: RU, place: room("B", 4) },
  ],
};
