import {
  BK,
  BLOCK_1,
  BLOCK_2,
  BLOCK_3,
  BLOCK_4,
  BLOCK_5,
  CH,
  D,
  EN_GK,
  EN_LK,
  ETH,
  FRZ,
  GE,
  LF_11,
  LF_6_7_9,
  LF_7_10,
  LF_8,
  LIT,
  MA_GK,
  MA_LK,
  PH,
  RU,
  SP,
  Timetable,
} from "../domain";

export const IGD21: Timetable = {
  mon: [
    { time: BLOCK_1, subject: MA_GK, place: "B 10"},
    { time: BLOCK_2, subject: LF_6_7_9, place: "B 8" },
    { time: BLOCK_3, iteration: 1, subject: GE, place: "B 4" },
    { time: BLOCK_3, iteration: 2, subject: EN_LK, place: "B 03" },
    { time: BLOCK_3, iteration: 2, subject: MA_LK, place: "B 11" },
    { time: BLOCK_4, subject: LF_11, place: "B 5", group: 1 },
    { time: BLOCK_4, subject: LF_8, place: "B 405", group: 2 },
    { time: BLOCK_5, iteration: 1, subject: EN_GK, place: "B 03" },
    { time: BLOCK_5, iteration: 2, subject: BK, place: "A 06" },
  ],
  tue: [
    { time: BLOCK_1, subject: LF_6_7_9, place: "B 8" },
    { time: BLOCK_2, subject: D, place: "B 6" },
    { time: BLOCK_3, subject: GE, place: "B 8" },
    { time: BLOCK_4, subject: ETH, place: "B 112" },
  ],
  wed: [
    { time: BLOCK_1, subject: FRZ, place: "A 102" },
    { time: BLOCK_1, subject: RU, place: "B 4" },
    { time: BLOCK_2, subject: CH, place: "B 9" },
    { time: BLOCK_3, subject: D, place: "B 6" },
    { time: BLOCK_4, subject: EN_LK, place: "B 03" },
    { time: BLOCK_4, subject: MA_LK, place: "B 11" },
    { time: BLOCK_5, iteration: 2, subject: LIT, place: "B 4"},
  ],
  thu: [
    { time: BLOCK_1, subject: PH, place: "B 106" },
    { time: BLOCK_2, subject: LF_8, place: "B 5", group: 1 },
    { time: BLOCK_2, subject: LF_11, place: "B 405", group: 2 },
    { time: BLOCK_3, subject: EN_GK, place: "B 05" },
    { time: BLOCK_3, subject: MA_GK, place: "B 11" },
    { time: BLOCK_4, subject: SP, place: "117.GS" },
  ],
  fri: [
    { time: BLOCK_1, subject: LF_7_10, place: "B 405", group: 1 },
    { time: BLOCK_2, subject: FRZ, place: "A 102" },
    { time: BLOCK_2, subject: RU, place: "B 4" },
    { time: BLOCK_3, subject: EN_LK, place: "B 6" },
    { time: BLOCK_3, subject: MA_LK, place: "B 11" },
    { time: BLOCK_4, iteration: 1, subject: LF_11, place: "B 5", group: 1 },
    { time: BLOCK_4, iteration: 1, subject: LF_8, place: "B 3", group: 2 },
    { time: BLOCK_4, iteration: 2, subject: LF_8, place: "B 3", group: 1 },
    { time: BLOCK_4, iteration: 2, subject: LF_11, place: "B 5", group: 2 },
  ],
};
