import {
  BK_1,
  BK_2,
  BlOCK_1,
  BlOCK_2,
  BlOCK_3,
  BlOCK_4,
  BlOCK_5,
  CH,
  D,
  EN,
  ETH,
  FRZ,
  GE,
  IS,
  LF_1_2,
  LF_5,
  LF_6,
  LIT,
  MA,
  PH,
  RU,
  SP,
  Timetable,
  W_R,
} from "../domain";

export const IGD21: Timetable = {
  mon: [
    { time: BlOCK_2, subject: W_R, place: "B 8" },
    { time: BlOCK_3, iteration: 1, subject: EN, place: "B 12" },
    { time: BlOCK_3, iteration: 2, subject: MA, place: "B 10" },
    { time: BlOCK_4, subject: LF_6, place: "B 411", group: 1 },
    { time: BlOCK_4, subject: IS, place: "B 3", group: 2 },
    { time: BlOCK_5, iteration: 2, subject: BK_1, place: "A 06" },
    { time: BlOCK_5, iteration: 2, subject: LIT, place: "B 4" },
  ],
  tue: [
    { time: BlOCK_1, subject: MA, place: "B 12" },
    { time: BlOCK_2, subject: EN, place: "B 204" },
    { time: BlOCK_3, subject: LF_1_2, place: "B 03" },
    { time: BlOCK_4, iteration: 1, subject: BK_2, place: "A 06" },
    { time: BlOCK_4, iteration: 2, subject: SP, place: "Kästner" },
  ],
  wed: [
    { time: BlOCK_1, subject: GE, place: "B 108" },
    { time: BlOCK_2, subject: IS, place: "B 3" },
    { time: BlOCK_3, iteration: 1, subject: ETH, place: "B 306" },
    { time: BlOCK_3, iteration: 2, subject: LF_5, place: "B 405" },
    { time: BlOCK_4, subject: FRZ, place: "A 102" },
    { time: BlOCK_4, subject: RU, place: "B 4" },
  ],
  thu: [
    { time: BlOCK_1, subject: D, place: "B 6" },
    { time: BlOCK_2, subject: MA, place: "B 10" },
    { time: BlOCK_3, subject: IS, place: "B 3" },
    { time: BlOCK_4, subject: PH, place: "B 110" },
  ],
  fri: [
    { time: BlOCK_1, subject: LF_6, place: "B 411", group: 1 },
    { time: BlOCK_1, subject: IS, place: "B 312", group: 2 },
    { time: BlOCK_2, subject: CH, place: "B 9" },
    { time: BlOCK_3, subject: D, place: "B 6" },
    { time: BlOCK_4, subject: FRZ, place: "A 102" },
    { time: BlOCK_4, subject: RU, place: "B 4" },
  ],
};
